title: 'slovejoy.github.io'
description: "Public Hackings from Renowed GUI Clicker Samuel Lovejoy"
baseurl: "/"
url: "https://slovejoy.github.io"

header_pages:
  - index.md
  - about.md
  - ctf.md

style: dark

# Build settings
markdown: kramdown
# theme: jekyll-theme-console
